### PR TITLE
Calculate RMS with sqrt((sum2-sum^2/n)/(n-1)).

### PR DESCRIPTION
**Pull request by inkdot7**
I believe the RMS calculation is not correct.  The commit also changes to print one decimal for the RMS.

With the update, I get things like:
```
               |          responses            |     TX timestamp offset (ns)
rate   clients |  lost invalid   basic  xleave |    min    mean     max      rms
10           1   0.00%   0.00% 100.00%   0.00%   +12181  +12543  +13477    326.6
15           1   0.00%   0.00% 100.00%   0.00%   +11792  +12125  +12631    188.8
22           2   0.00%   0.00% 100.00%   0.00%   +11082  +12045  +12906    284.1
```
with the previous (note e.g. how the RMS is larger than the difference max-min in the rate 15 row).
```
               |          responses            |     TX timestamp offset (ns)
rate   clients |  lost invalid   basic  xleave |    min    mean     max    rms
10           1   4.76%   0.00%  95.24%   0.00%   +14914  +17277  +53525  19177
15           1   6.45%   0.00%  93.55%   0.00%   +22210  +26470  +39530  26791
22           2   0.00%   0.00% 100.00%   0.00%   +14669  +19872 +129781  26092
```

### CODE REVIEW

**Comment by mlichvar** [comment]
Which definition of RMS are you using? The common one is literally just the root of mean square:

https://en.wikipedia.org/wiki/Root_mean_square

You want to see standard deviation instead of RMS?

The change in formatting causes the output to not fit in 80-column terminal.

**Comment by inkdot7** [comment]
Ahh, yes.  I think the standard deviation would be more informative to see.  Should have called it std or stddev instead then.

And also sorry about missing the 80-column limit.  One more character seems to be available, though.

I updated the commit.

**Comment by inkdot7** [comment]
Though, the added decimal is perhaps not very useful, as I just realized that the 'response time (ns)' is the remote response time only, not the roundtrip time.  Perhaps could be changed to 'server response time (ns)' or 'remote response time (ns)'.

**Comment by mlichvar** [comment]
Please split it into two commits.

Ok, stddev might be better, but that calculation doesn't seem correct to me. Do you have a reference? I think you would need to accumulate another sum (difference to current and previous mean).

**Comment by inkdot7** [comment]
It should match the calculation in the code box at https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Na%C3%AFve_algorithm
(Aha, the routines below that can handle those cases without the cancellation losses, but are more complicated.  Perhaps one can argue that for a test program like this, it is not needed.  If someone has a large offset and a fancy small std.dev., they would anyhow first shift that away the offset.)

**Comment by mlichvar** [comment]
Ok, I was thinking about the Welford's algorithm. If the square root gets a negative number, the stddev would be a NaN, but I guess that's acceptable.

Can you change the "/(n - 1" to "/n"? I think "finite population" would fit here better.

And maybe drop the formula from the commit subject?

**Comment by inkdot7** [comment]
Thanks for pointing out Welford's algorithm!  I have changed to use that.  (I did test to see that it generates the same values as the more naive approach).

For the /(n-1), I and a colleague had some 'fun' trying to follow https://en.wikipedia.org/wiki/Bessel%27s_correction#Source_of_bias .  The section https://en.wikipedia.org/wiki/Bessel%27s_correction#Intuition turned out easier to digest.

Then also found https://en.wikipedia.org/wiki/Unbiased_estimation_of_standard_deviation#Rule_of_thumb_for_the_normal_distribution which suggest to use /(n-1.5) when estimating a standard deviation.

We also made a small experiment for different n with octave/matlab to see this in practice (averaging 10000 experiments for each n):

```
b=[];
c=[];
for n=[2:10, 20, 50, 100];
  a=randn(n,10000);    % random numbers with mean 0 and variance 1
  xx = sum(a(1:n,:).*a(1:n,:));
  x  = sum(a(1:n,:));
  varest_n   = (xx-x.*x./n)/(n);
  stdest_n   = sqrt(varest_n);
  varest_n1  = (xx-x.*x./n)/(n-1);
  stdest_n1  = sqrt(varest_n1);
  varest_n15 = (xx-x.*x./n)/(n-1.5);
  stdest_n15 = sqrt(varest_n15);
  b=[b; n, mean(varest_n) mean(varest_n1) mean(varest_n15) mean(stdest_n) mean(\
stdest_n1) mean(stdest_n15)];
  % c=[c; n, std(varest_n) std(varest_n1) std(varest_n15) std(stdest_n) std(std\
est_n1) std(stdest_n15)];
end
b
% format short g
% c
```
which gives (header added)
```
     n          --------- variance ---------     --------- std. dev. --------
                /n         /(n-1)     /(n-1.5)   /n         /(n-1)     /(n-1.5)

     2.0000     0.5068     1.0137     2.0273     0.5655     0.7997     1.1310
     3.0000     0.6754     1.0132     1.3509     0.7270     0.8904     1.0282
     4.0000     0.7644     1.0193     1.2231     0.8066     0.9314     1.0203
     5.0000     0.8001     1.0001     1.1430     0.8407     0.9400     1.0049
     6.0000     0.8424     1.0109     1.1233     0.8743     0.9577     1.0095
     7.0000     0.8485     0.9899     1.0799     0.8840     0.9548     0.9973
     8.0000     0.8724     0.9971     1.0738     0.9019     0.9642     1.0006
     9.0000     0.8965     1.0086     1.0758     0.9177     0.9734     1.0053
    10.0000     0.8975     0.9973     1.0559     0.9216     0.9714     0.9996
    20.0000     0.9515     1.0016     1.0287     0.9631     0.9881     1.0013
    50.0000     0.9785     0.9985     1.0088     0.9841     0.9941     0.9992
   100.0000     0.9899     0.9999     1.0050     0.9924     0.9974     0.9999
```
The middle column for variance comes closest to being around 1 independent of n also for small n.  (It really should remove the entire bias.)  For the std. dev. estimate, the approximate correction with -1.5 is better.  I think really small n are not much used for `ntpperf`, so the remaining bias should be acceptable.

**Comment by inkdot7** [comment]
I also removed the decimal printing for the std.dev. in the PR.  It turned out to come from me looking at the wrong numbers.  If I find a case with such a small std.dev., I'll come with a patch that prints small numbers only with decimals, to conserve space.

**Comment by mlichvar** [comment]
It seems to work nicely. Applied, thanks!

**Pull request closed without merging**
